config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  namespace :owner do
    resources :bookings, only: [:index]
    resources :tours, only: [:index]
  end

  resources :tours, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :tour

  PARTICIPANTS = [ 1, 2, 3, 4, 5]

  # Validations

  validates :schedule, presence: true

  # validates :schedule, inclusion: { in: TIMESLOT }

  validates :participant, presence: true
  enum confirmation: {
    pending: 0,
    confirmed: 1,
    declined: 2
  }
end

app/models/tour.rb
class Tour < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Associations
  belongs_to :user # Owner user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings # Client user
  has_one_attached :photo

#  TIME = [Time.]

  # Validations
  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: true
  validates :content, presence: true, length: { minimum: 10 }

  include PgSearch::Model  #Added PG Search , not sure how to use exactly
  pg_search_scope :search_by_address,
    against: [ :address],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Associations
  has_many :bookings
  has_many :bookings_as_owner, through: :tours, source: :bookings
  has_many :tours

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, numericality: { greater_than: 19 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:update]

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def create
    raise
    @tour = Tour.find(params[:tour_id])
    @booking = Booking.new(booking_params) #need to give it tour
    @booking.tour = @tour
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render tour_path(@tour)
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to owner_bookings_path
    else
      redirect_to owner_bookings_path #fix later, to right page
    end
  end

    private
    def set_booking
      @booking = Booking.find(params[:id])
      authorize @booking
    end

    def booking_params
      params.require(:booking).permit(:schedule, :confirmation)
    end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = policy_scope([:owner, Booking]).order(created_at: :desc)
  end
end

app/controllers/owner/tours_controller.rb
class Owner::ToursController < ApplicationController
  def index
    @tours = policy_scope([:owner, Tour]).order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ] # :show if we want to
  def index
    @tours = policy_scope(Tour).order(created_at: :desc)
    if params[:query].present?
      tours = policy_scope(Tour).search_by_address(params[:query]).order(created_at: :desc)
      @tours = tours
    else
      @tours = policy_scope(Tour).order(created_at: :desc)
    end
    @markers = @tours.geocoded.map do |tour|
      { lat: tour.latitude,
        lng: tour.longitude }
    end
  end

  def show
    @tour = Tour.find(params[:id])
    authorize @tour
    @booking = Booking.new
  end

  def new
    @tour = Tour.new
    authorize @tour
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user
    authorize @tour
    if @tour.save
      redirect_to tours_path
    else
      render :new
    end
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :address, :price, :content, :duration, :start_time, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">My bookings</h1>
  <% if @bookings.length == 0 %>
    <h2>No bookings yet</h2>
  <% else %>
    <% @bookings.each do |booking| %>
      <div class="card-no-hover mb-4 p-4 border border-primary border-2">
        <div class="ms-4 card-product-infos">
          <h2><%= booking.tour.name %></h2>
          <p>Your booking time: <%= booking.schedule %></p>
          <p><%= booking.tour.content %></p>
          <p><%= booking.user.first_name %></p>
          <p>Booking status : <span class="<%= booking.confirmation == 'confirmed' ? "text-success" : "text-warning" %>"><%= booking.confirmation %></span></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyTour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="container">
  <h1 class = "m-4">Your Bookings</h1>
  <% @bookings.each do |booking|%>
    <div class="card-no-hover m-4 p-4 border border-primary border-2">
      <h2><%= booking.tour.name %></h2>
      <p><%= booking.schedule %></p>
      <div class="d-flex">
        <% if booking.pending? %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :confirmation, as: :hidden, input_html: { value: 'confirmed'} %>
            <%= f.submit 'Accept', class: 'btn btn-info me-3 border-2' %>
          <% end %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :confirmation, as: :hidden, input_html: { value: 'rejected'} %>
            <%= f.submit 'Reject', class: 'btn btn-danger text-white border-2' %>
          <% end %>
          <!-- Display Forms-->
        <% else %>
          <!-- Display Status-->
          <p class='booking-tag'><%= booking.confirmation %></p>
        <% end %>
      </div>
        </div>

    <% end %>
</div>

app/views/owner/tours/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Your Tours</h1>
  <% if @tours.length == 0 %>
    <h2>No tours added yet</h2>
  <% else %>
    <% @tours.each do |tour| %>
      <%= render "tours/tour", tour: tour %>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="background-photo d-inline-flex justify-content-center align-items-center">
  <div class="container w-50 text-center align-items-center">
    <h1>Explore Local Breweries</h1>
    <%= form_tag tours_path, method: :get, class:"d-flex align-items space-beween" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Start now"
        %>
        <%= submit_tag "search", class:"button rounded-0 rounded-left" %>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div id="bookingModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Tour is booked!</h4>
      </div>
      <div class="modal-body">
        <p>Wait for confirmation update from the brewery</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://i.ibb.co/42sYjZg/logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <li class="nav-item button">
          <%= link_to 'See all Tours', tours_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          &nbsp;
          &nbsp;
          &nbsp;
          <li class="nav-item dropdown">
            <%= image_tag "https://images.pexels.com/photos/1552630/pexels-photo-1552630.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, method: :get, class: "dropdown-item" %>
              <%= link_to "Add a new tour", new_tour_path, method: :get, class: "dropdown-item" %>
              <% if current_user.tours.any? %>
                <%= link_to "Manage your Tours", owner_tours_path, method: :get, class: "dropdown-item" %>
                <%= link_to "Your cutomer's bookings", owner_bookings_path, method: :get, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item button ms-3">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tours/_tour.html.erb
<div class="card-product mb-4 p-4 border border-primary border-2">
  <%= image_tag(tour.photo.attached? ? cl_image_path(tour.photo.key) : "brew_photos/#{rand(12)}.jpg") %>
  <div class="ms-4 card-product-infos">
    <h2><%= tour.name %></h2>
    <small><%= tour.address %></small>
    <p class="card-content"><%= tour.content %></p>
    <p><strong>¥<%= tour.price %></strong><small>/pp</small></p>
    <%= link_to '', tour_path(tour), class: 'card-link' %>
  </div>
</div>

app/views/tours/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6" id="top-div">
      <h1 class="mt-4 mb-4"><strong><%= @tours.length %></strong> HappyTours are Available</h1>
      <% @tours.each do |tour| %>
        <%= render "tours/tour", tour: tour %>
      <% end %>
    </div>
    <div class="col-lg-6 mt-5" id="map">
      <div class="index-right" style="width: 100%; height: 100vh;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/tours/new.html.erb
<div class="container">
  <div class = "card-no-hover p-4 m-4 border border-primary border-2">
    <h1 class="mt-4 mb-4">Add a new tour</h1>
    <%= simple_form_for(@tour) do |f| %>
      <%= f.input :name, placeholder: 'Name of the tour' %>
      <%= f.input :address, placeholder: 'Address' %>
      <%= f.input :price, value: '¥1200' %>
      <%= f.input :content, placeholder: 'Please explain the contant of your tour...' %>
      <%= f.input :start_time, html5: true %>
      <%= f.input :duration, :collection => 1..5 %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: 'button mt-2 wt-100' %>
    <% end %>
  </div>
</div>

app/views/tours/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
</div>
<div class="container mt-4 pt-4">
  <h1 class=" mb-4"><%= @tour.name %></h1>
  <div class="row">
    <div class="col-md-8">
      <div class="card-no-hover mb-4 p-4 border border-primary border-2">
        <h3>Starting at ¥<%= @tour.price %></h3>
        <p><%= @tour.address %></p>
        <p><%= @tour.content %></p>
      </div>
      <div class="card-no-hover mb-4 p-4 border border-primary border-2">
        <h3>About the Tour Guide</h3>
        <p>Brewer of <%= @tour.name %></p>
        <p>The owner loves to drink all day!</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-no-hover mb-4 p-4 border border-primary border-2">
        <div class="d-flex justify-content-between mt-3">
          <h3>Request a Tour</h3>
        </div>
        <!-- date may require to be connected to db -->
        <div class="form-group mb-3">
        </div>
        <strong>
          <div class="d-flex justify-content-between mt-3">
          </div>
          <% if user_signed_in? %>
            <div class="d-flex justify-content-end mb-3">
              <h2><%= number_to_currency(@tour.price, {unit: '¥', precision: 0}) %> Per Person</h2>
            </div>
            <%= simple_form_for [ @tour, @booking ] do |f| %>
              <p><%= @tour.duration%> hour tour with drinks</p>
              <%# <%= f.input :start_time, html5: true %>
              <%= f.input :schedule, collection: [@tour.start_time.strftime("%H:%M on %m/%d/%Y") ] %>
              <%= f.input :participant, html5: true %>
              <% if @tour.user != current_user %>
                <%= f.submit class: "btn btn-primary w-100 rounded-8" %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary w-100 rounded-8" %>
          <% end %>
        </div>
      </div>
      <%# <a href="#" class="btn btn-primary w-100 rounded-8">Checkout</a> %>
    </div>
  </div>
</div>
</div>
</div>
<!-- Trigger the modal with a button -->